export enum ACCOUNT_STATUS {
  PENDING = 'PENDING',
  ACTIVE = 'ACTIVE',
  INACTIVE = 'INACTIVE',
  DELETED = 'DELETED'
}

export enum ACCOUNT_TYPE {
  ADMIN = 'ADMIN',
  COMPANY = 'COMPANY',
  USER = 'USER',
  PROFESSIONAL = 'PROFESSIONAL'
}
