export enum ComparatorEnum {
  EQUALS = 'EQUALS',
  NOT_EQUALS = 'NOT_EQUALS',
  GREATER_THAN = 'GREATER_THAN',
  GREATER_THAN_OR_EQUALS = 'GREATER_THAN_OR_EQUALS',
  LESS_THAN = 'LESS_THAN',
  LESS_THAN_OR_EQUALS = 'LESS_THAN_OR_EQUALS',
  CONTAINS = 'CONTAINS',
  NOT_CONTAINS = 'NOT_CONTAINS',
  IN = 'IN',
  NOT_IN = 'NOT_IN',
  BETWEEN = 'BETWEEN',
  NOT_BETWEEN = 'NOT_BETWEEN'
}

export enum DefinitionEnum {
  IP = 'IP',
  ALL_USERS = 'ALL_USERS',
  EMAIL = 'EMAIL',
  ID = 'ID',
  NAME = 'NAME',
  AGE = 'AGE',
  COUNTRY = 'COUNTRY',
  STATE = 'STATE',
  DEVICE = 'DEVICE',
  BROWSER = 'BROWSER',
  PLATFORM = 'PLATFORM',
  LANGUAGE = 'LANGUAGE',
  REFERRER = 'REFERRER'
}
