export enum ErrorType {
  IS_NOT_STRING = 'IS_NOT_STRING',
  IS_NOT_NUMBER = 'IS_NOT_NUMBER',
  IS_NOT_BOOLEAN = 'IS_NOT_BOOLEAN',
  IS_NOT_DATE = 'IS_NOT_DATE',
  IS_NOT_EMAIL = 'IS_NOT_EMAIL',
  IS_NOT_STATUS = 'IS_NOT_STATUS',
  IS_NOT_TYPE = 'IS_NOT_TYPE',
  IS_NOT_DEFINED = 'IS_NOT_DEFINED',
  LENGTH = 'LENGTH'
}

export enum AccountErrorType {
  ACCOUNT_ALREADY_EXISTS = 'ACCOUNT_ALREADY_EXISTS',
  PROFESSIONAL_ACCOUNT_INCOMPLETE = 'PROFESSIONAL_ACCOUNT_INCOMPLETE',
  ACCOUNT_DOES_NOT_EXIST = 'ACCOUNT_DOES_NOT_EXIST',
  UNAUTHORIZED = 'UNAUTHORIZED'
}

export enum ProjectErrorType {
  PROJECT_ALREADY_EXISTS = 'PROJECT_ALREADY_EXISTS',
  PROJECT_DOES_NOT_EXIST = 'PROJECT_DOES_NOT_EXIST'
}

export enum OrganizationErrorType {
  ORGANIZATION_ALREADY_EXISTS = 'ORGANIZATION_ALREADY_EXISTS',
  ORGANIZATION_DOES_NOT_EXIST = 'ORGANIZATION_DOES_NOT_EXIST',
  INTERNAL_SERVER_ERROR = 'INTERNAL_SERVER_ERROR'
}

export enum FeatureErrorType {
  FEATURE_ALREADY_EXISTS = 'FEATURE_ALREADY_EXISTS',
  FEATURE_DOES_NOT_EXIST = 'FEATURE_DOES_NOT_EXIST'
}

export enum VariationErrorType {
  VARIATION_ALREADY_EXISTS = 'VARIATION_ALREADY_EXISTS',
  VARIATION_TYPE_INVALID = 'VARIATION_TYPE_INVALID',
  VARIATION_DOES_NOT_EXIST = 'VARIATION_DOES_NOT_EXIST',
  VARIATION_ID_FROM_ANOTHER = 'VARIATION_ID_FROM_ANOTHER'
}

export enum RuleErrorType {
  RULE_ALREADY_EXISTS = 'RULE_ALREADY_EXISTS',
  RULE_DOES_NOT_EXIST = 'RULE_DOES_NOT_EXIST'
}

export interface JsonApiError {
  statusCode?: number;
  code?: string;
  title?: string;
  detail?: string;
  source?: {
    pointer?: string;
  };
}
